### ISSUE TITLE
Sources listed under New Texts are not selectable or clickable

### ISSUE THREAD

**Issue by aharonium** [opensiddur/opensiddur-client#48]
After clicking new under "Texts," there is an index of sources but these are not selectable or clickable. Only after the item item title is entered in what appears to be a search field does the NEW button become active. There is also what appears to be an additional search field below these other entry fields. This is all confusing.

I had to copy and paste the text in that list to the search form's "document title" before the NEW button became active.

If an item appears in that list, clicking on it should open the editing form without needing to click on the NEW button.

**Comment by EfraimFeinstein** [comment]
Cannot reproduce.
The sources are selectable/clickable both before and after a title is inserted.

The New button works as expected if all the required fields (including a title) are filled out. Not having a title is simply not possible.

There is only 1 search box and it is for sources.

Clicking *should not* automatically open anything. If I want to transcribe/edit "Adon Olam" from the Singer Siddur source, I have to enter the fact that I'm transcribing Adon Olam (the title) and also select that the source is the Singer Siddur. I also don't want an accidental click to lose work in the dialog. I also have to select the license, etc.

If you're using Firefox, the scrollbar is currently not displaying, which is a known bug.
