### ISSUE TITLE
Transcription button identifies incorrect source

### ISSUE THREAD

**Issue by aharonium** [opensiddur/opensiddur-client#49]
I added a source "A Prayer for the Prosperitie of his Royal Majestie," added the text and saved it. I then clicked on the transcription button expecting to see the page from the Internet Archive that I saved in the Source form. Alas, the transcription form seems to be disassociated from that source. See image.

![capture](https://cloud.githubusercontent.com/assets/855510/10440580/9b436690-710e-11e5-96d7-104178527d44.PNG)

**Comment by EfraimFeinstein** [comment]
I can't reproduce this as a *bug*. After adding the source and pressing the prominent "Refresh" button on the right side of the sources, the source is correctly displayed in the dropdown menu.

One might ask why the refresh action shouldn't just happen when you edit a source, but that's an enhancement request, not a bug :-)

(Incidentally, I doubt you really intended the entire text to be one segment.)

**Comment by aharonium** [comment]
Yeah, add this to the issue list, I had a lot of trouble using the segmentation button as well. The button didn't seem to be active when I was clicking on it. I think we should add a statement on the front page indicating what browsers we know to support the interface. (Mozilla Nightly and Chrome Canary weren't working for me.)

**Comment by EfraimFeinstein** [comment]
If you think the segmentation button doesn't work, add another issue. One
warning: Pre-release browsers will *never* be supported. Try a released
version of Firefox or Chrome. There isn't yet much automated testing (code
coverage is probably under 1% now). What does exist targets recent releases
of Chrome and Firefox.

You don't need to hit the segmentation button (that's only used to edit
details like xml:id or text language if it's something other than the
default for the text), pressing enter will create a new segment.

**Comment by aharonium** [comment]
Trying to remember, I think I was only able to get as far as I did using regular Chrome 45. In any case, I'm not clear on what I should have segmented out in that prayer. Wasn't there supposed to be an auto-segmenting step?

**Comment by EfraimFeinstein** [comment]
No. Auto-segmenting can't do anything in simple mode. All that
auto-segmenting does is this: In XML editing mode, you can press enter
between segments without entering <tei:seg> elements and if you press
auto-segment, it will add the <tei:seg xml:id="somethingrandom"></tei:seg>
tags so you don't have to do it manually. In simple mode, pressing enter
adds the tags with no additional button presses.

**Comment by aharonium** [comment]
Clearly, at that phase of the process of inputting text, I'm a bit lost. It has to be clear in the GUI what the user is expected to do.

**Comment by EfraimFeinstein** [comment]
I believe the original issue is fixed. Sources now show up in the drop down after being added and disappear after being removed without having to press the "refresh" button.
