### ISSUE TITLE
Error on Saving New Bibliographic Entry

### ISSUE THREAD

**Issue by aharonium** [opensiddur/opensiddur-client#50]
Input document is not valid
attribute "key" not allowed here; expected attribute "cert", "n", "rend", "rendition", "resp", "style", "when", "xml:id" or "xml:lang"
WARNING: use of deprecated method — the use of the idno element as a direct child of the biblStruct element will be removed from the TEI on 2016-09-18

---
Browser is Chromium
Version 48.0.2548.0 (64-bit)

(same behavior in Chrome Version 46.0.2490.80 m (64-bit))

![capture](https://cloud.githubusercontent.com/assets/855510/10762007/7083e8b6-7c9a-11e5-8de4-839ddb7938ab.PNG)

**Comment by EfraimFeinstein** [comment]
This turned out to be an error in the schema. It is corrected now.
