### ISSUE TITLE
Cannot locate "saved" text

### ISSUE THREAD

**Issue by aharonium** [opensiddur/opensiddur-client#52]
The "saved" text, מוֺדֶה אֲנִי, should be found at http://app.opensiddur.org/texts/%D7%9E%D7%95%D6%BA%D7%93%D6%B6%D7%94%20%D7%90%D6%B2%D7%A0%D6%B4%D7%99 but it not.

Text had been saved in an earlier session (saved button was green) but the text cannot be retrieved.

**Comment by EfraimFeinstein** [comment]
Not a bug. The URL is wrong. Titles can have vowels. URLs never have vowels. 

app.opensiddur.org/stexts/מודה%20אני
